spring:
  application:
    name: aptio-api

  # Multipart File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/aptiodb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Use 'update' for production, 'create-drop' for development
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  # SQL Initialization
  sql:
    init:
      mode: always  # Always run SQL scripts
      continue-on-error: true

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

# JSON Web Token Configuration
jwt:
  secret: aptioSecretKey2025VerySecureKeyForJwtTokenGeneration
  expiration: 86400000  # 24 hours in milliseconds

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

# Logging Configuration
logging:
  level:
    org.springframework: INFO
    com.aptio: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# CORS Configuration
cors:
  allowed-origins: http://localhost:4200/
  allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowed-headers: Origin,Content-Type,Accept,Authorization
  exposed-headers: Authorization
  allow-credentials: true
  max-age: 3600

# Application-specific Initialization Settings
app:
  initialization:
    create-demo-data: true

